# Uncomment the next line to define a global platform for your project

  platform :ios, '10.0'

def thirdLibs
  # third libs
  pod 'Protobuf', '3.17.0'
  pod "CocoaLumberjack", '3.6.1'
  pod 'AliyunOSSiOS',  '2.10.8'
  pod 'Armin',  '1.1.0'
  pod 'SSZipArchive', '2.4.2'
  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry', '1.1.0'
  pod 'SDWebImage', '5.12.0'

  # agora libs
  pod 'AgoraRtm_iOS', '1.4.8'
  pod 'AgoraMediaPlayer_iOS', '1.3.0'
  pod 'Whiteboard', '2.16.39'
  pod 'Agora_Chat_iOS', '1.0.6'
end

def preRtc
  pod 'AgoraEduCore/Binary', :path => '../../../cloudclass-ios/AgoraEduCore_Local.podspec'
  pod "AgoraRtcEngine_iOS/RtcBasic", "3.6.2"
end

def reRtc
  pod 'AgoraEduCore/Binary', :path => '../../../cloudclass-ios/AgoraEduCore_Local.podspec'
  pod 'AgoraRtcKit', :path => '../../../common-scene-sdk/ReRtc/AgoraRtcKit_Binary.podspec'
end

target 'AgoraBuilder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  post_install do |installer|
     installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
          config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
     end
  end
end
