# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

def libVersion
  # third libs
  pod 'Protobuf', '3.17.0'
  pod "CocoaLumberjack", '3.6.1'
  pod 'AliyunOSSiOS',  '2.10.8'
  pod 'Armin',  '1.0.10'
  pod 'Alamofire', '4.7.3'
  pod 'SSZipArchive', '2.4.2'
  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry', '1.1.0'
  pod 'SDWebImage', '5.12.0'
  pod 'WHToast', '0.0.7'
  pod 'FLAnimatedImage', '1.0.16'

  # agora libs
  pod 'AgoraRtm_iOS', '1.4.8'
  pod 'Whiteboard', '2.16.17'
  pod 'AgoraRtcEngine_iOS/RtcBasic', '3.7.2'
  pod 'HyphenateChat', '3.8.6'
end

def preRtc
  pod 'AgoraEduCore/PreRtc', :path => '../../../cloudclass-ios/AgoraEduCore_Local.podspec'
  pod 'AgoraRte/PreRtc', :path => '../../../common-scene-sdk/iOS/AgoraRte.podspec'
end

def openSourceLibs
  # open source libs
  pod 'AgoraClassroomSDK_iOS', :path => '../AgoraClassroomSDK/AgoraClassroomSDK_Local.podspec'
  pod 'AgoraEduContext', :path => '../AgoraEduContext/AgoraEduContext_Local.podspec' 
  pod 'AgoraEduUI', :path => '../AgoraEduUI/AgoraEduUI_Local.podspec'

  pod 'AgoraWidgets', :path => '../../../open-apaas-extapp-ios/AgoraWidgets/AgoraWidgets_Local.podspec'
end

def closeSourceLibs
  # close source libs
  pod 'AgoraReport', :path => '../../../apaas-common-libs-ios/SDKs/AgoraReport/AgoraReport.podspec'
  pod 'AgoraRx', :path => '../../../apaas-common-libs-ios/SDKs/AgoraRx/AgoraRx.podspec'
	
  # common libs
  pod 'AgoraWidget', :path => '../../../apaas-common-libs-ios/SDKs/AgoraWidget/AgoraWidget_Local.podspec'
  pod 'AgoraUIBaseViews', :path => '../../../apaas-common-libs-ios/SDKs/AgoraUIBaseViews/AgoraUIBaseViews_Local.podspec'  

  # rtc
  preRtc
end


target 'AgoraBuilder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  libVersion
  
  openSourceLibs
  
  closeSourceLibs
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end

      target.build_configurations.each do |config|
        config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
