# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

def sourcePod
  # open source libs
  pod 'AgoraEduContext', :path => '../AgoraEduContext/AgoraEduContext.podspec'
  pod 'AgoraUIEduBaseViews', :path => '../Modules/AgoraUIEduBaseViews/AgoraUIEduBaseViews.podspec', :subspecs => ['SOURCE']

  # common libs
  pod 'AgoraUIBaseViews', :path => '../../../apaas-common-libs-ios/SDKs/AgoraUIBaseViews/AgoraUIBaseViews.podspec'
  pod 'AgoraExtApp', :path => '../../../apaas-common-libs-ios/SDKs/AgoraExtApp/AgoraExtApp.podspec'
  pod 'AgoraWidget', :path => '../../../apaas-common-libs-ios/SDKs/AgoraWidget/AgoraWidget.podspec'
end

def binaryPod
  pod 'AgoraUIBaseViews', :path => '../AgoraUIBaseViews/AgoraUIBaseViews.podspec'
  pod 'AgoraUIEduBaseViews', :path => '../AgoraUIEduBaseViews/AgoraUIEduBaseViews.podspec', :subspecs => ['SUMBINARY']
  pod 'AgoraBaseBinary', :path => './AgoraBaseBinary.podspec'
end

target 'AgoraEduUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  sourcePod
end
