# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

def openSourceLibs
  pod 'AgoraEduContext', :path => '../AgoraEduContext/AgoraEduContext.podspec'
  pod 'AgoraUIEduBaseViews', :path => '../Modules/AgoraUIEduBaseViews/AgoraUIEduBaseViews.podspec'
end

def sourcePod
  # open source libs
  openSourceLibs

  # common libs
  pod 'AgoraUIBaseViews', :path => '../../../apaas-common-libs-ios/SDKs/AgoraUIBaseViews/AgoraUIBaseViews_Local.podspec'
  pod 'AgoraExtApp', :path => '../../../apaas-common-libs-ios/SDKs/AgoraExtApp/AgoraExtApp_Local.podspec'
  pod 'AgoraWidget', :path => '../../../apaas-common-libs-ios/SDKs/AgoraWidget/AgoraWidget_Local.podspec'
end

def binaryPod
  pod 'AgoraUIBaseViews'
  pod 'AgoraExtApp'
  pod 'AgoraWidget'
end

target 'AgoraEduUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  openSourceLibs
  sourcePod
end
