# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def sourcePod
  pod 'AgoraUIBaseViews', :path => '../../../../apaas-common-libs-ios/SDKs/AgoraUIBaseViews/AgoraUIBaseViews_Local.podspec'
end

def binaryPod
  pod 'AgoraUIBaseViews'
end

target 'AgoraUIEduBaseViews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  sourcePod
end
