# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

def sourcePod
  pod 'AgoraUIBaseViews', :path => '../AgoraUIBaseViews/AgoraUIBaseViews.podspec'
  pod 'AgoraUIEduBaseViews', :path => '../AgoraUIEduBaseViews/AgoraUIEduBaseViews.podspec', :subspecs => ['SOURCE']
  pod 'AgoraExtApp', :path => '../AgoraExtApp/AgoraExtApp.podspec'
  pod 'AgoraEduContext', :path => '../AgoraEduContext/AgoraEduContext.podspec'
  pod 'AgoraWidget', :path => '../AgoraWidget/AgoraWidget.podspec'
end

def binaryPod
  pod 'AgoraUIBaseViews', :path => '../AgoraUIBaseViews/AgoraUIBaseViews.podspec'
  pod 'AgoraUIEduBaseViews', :path => '../AgoraUIEduBaseViews/AgoraUIEduBaseViews.podspec', :subspecs => ['SUMBINARY']
  pod 'AgoraBaseBinary', :path => './AgoraBaseBinary.podspec'
end

target 'AgoraUIEduAppViews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  sourcePod
end
