# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AgoraEduSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AgoraLog', :path => '../AgoraLog/AgoraLog.podspec'
  pod 'EduSDK', :path => '../EduSDK/EduSDK.podspec'
  pod 'AgoraWhiteBoard', :path => '../AgoraWhiteBoard/AgoraWhiteBoard.podspec'

  pod 'AgoraReplay', :path => '../AgoraReplay/AgoraReplay.podspec'
  pod 'AgoraReplayUI', :path => '../AgoraReplayUI/AgoraReplayUI.podspec'

#  # if you use swift project, you just only change 'OC' to 'Swift'
#  pod 'AgoraHandsUp', :path => '../AgoraHandsUp/AgoraHandsUp.podspec', :subspecs => ['OC']
#
#  # if you use swift project, you just only change 'OC' to 'Swift'
#  pod 'AgoraActionProcess', :path => '../AgoraActionProcess/AgoraActionProcess.podspec', :subspecs => ['OC']

  post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
             config.build_settings['ENABLE_BITCODE'] = 'YES'
         end
     end
  end
end
