# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AgoraEduSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AgoraLog', :path => '../AgoraLog/AgoraLog.podspec'
  pod 'EduSDK', :path => '../EduSDK/EduSDK.podspec'
  pod 'AgoraWhiteBoard', :path => '../AgoraWhiteBoard/AgoraWhiteBoard.podspec'

  pod 'AgoraReport', :path => '../AgoraReport/AgoraReport.podspec'

  pod 'AgoraUIBaseViews', :path => '../AgoraUIBaseViews/AgoraUIBaseViews.podspec'
  pod 'AgoraUIEduAppViews', :path => '../AgoraUIEduAppViews/AgoraUIEduAppViews.podspec', :subspecs => ['SOURCE']
  pod 'AgoraUIEduBaseViews', :path => '../AgoraUIEduBaseViews/AgoraUIEduBaseViews.podspec', :subspecs => ['SOURCE']

  pod 'AgoraExtApp', :path => '../AgoraExtApp/AgoraExtApp.podspec'
  pod 'AgoraWidget', :path => '../AgoraWidget/AgoraWidget.podspec'
	
  pod 'AgoraEduContext', :path => '../AgoraEduContext/AgoraEduContext.podspec'
  pod 'AgoraEduExtApp', :path => '../AgoraEduExtApp/AgoraEduExtApp.podspec'
  
  # if you use swift project, you just only change 'OC' to 'Swift'
  pod 'AgoraActionProcess', :path => '../AgoraActionProcess/AgoraActionProcess.podspec', :subspecs => ['OC']
  
  pod 'Protobuf'

  post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
             config.build_settings['ENABLE_BITCODE'] = 'YES'
             config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
         end
     end
  end
end
