platform :ios, '10.0'
inhibit_all_warnings!
 
workspace 'AgoraEducation.xcworkspace'
install! 'cocoapods', :deterministic_uuids => false, :warn_for_unused_master_specs_repo => false
 
target 'AgoraEducation' do
  use_frameworks!
 
  # third libs
  pod 'OpenSSL-Universal', '1.0.2.17'
  pod 'Protobuf', '3.17.0'
  pod "CocoaLumberjack", '3.6.1'
  pod 'AliyunOSSiOS',  '2.10.8'
  pod 'Armin',  '1.0.9'
  pod 'Alamofire', '4.7.3'
  pod 'SSZipArchive', '2.4.2'
  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry'
  pod 'SDWebImage', '5.12.0'
 
  # agora libs
  pod 'AgoraRtm_iOS', '1.4.8'
  pod 'Whiteboard', '2.15.16'
  pod 'AgoraRtcEngine_iOS', '3.4.6'
  pod 'HyphenateChat', '3.8.6'
 
  # open source libs
  pod 'AgoraClassroomSDK_iOS', :path => '../SDKs/AgoraClassroomSDK/AgoraClassroomSDK_iOS.podspec'
  pod 'AgoraEduContext', :path => '../SDKs/AgoraEduContext/AgoraEduContext.podspec'
  pod 'AgoraEduUI', :path => '../SDKs/AgoraEduUI/AgoraEduUI.podspec'
   
  # open sources widgets and extApps
  pod 'AgoraWidgets', :path => '../../apaas-extapp-ios/Widgets/AgoraWidgets/AgoraWidgets.podspec'
  pod 'ChatWidget', :path => '../../apaas-extapp-ios/Widgets/ChatWidget/ChatWidget.podspec'
  pod 'AgoraExtApps', :path => '../../apaas-extapp-ios/ExtApps/AgoraExtApps.podspec'
   
  # close source libs
  pod 'AgoraEduCore', '2.0.0'
end
