# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'AgoraBuilder' do
  # Comment the next line if you don't want to use dynamic frameworks

  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry',      '1.1.0'  

  use_frameworks!

  #ContentStartIndex
  
  #ContentEndIndex
end

# post install
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        
      # no signing for pods bundle, after xcode 14
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
        
      # reset libs version
      deployment = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']

      if deployment.to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end

      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
