# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AgoraReplayUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgoraReplayUI
  pod 'AgoraReplay', :path => '../AgoraReplay/AgoraReplay.podspec'
  pod 'AgoraLog', :path => '../AgoraLog/AgoraLog.podspec'
  pod "Whiteboard", "2.12.26"

  post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
             config.build_settings['ENABLE_BITCODE'] = 'YES'
         end
     end
  end
end
