# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgoraExtApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform:ios, '10.0'

  # Pods for AgoraExtApp
  pod 'AgoraUIBaseViews', :path => '../AgoraUIBaseViews/AgoraUIBaseViews.podspec'
end
