# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgoraEduExtApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgoraEduExtApp
  pod 'AgoraUIBaseViews', :path => '../AgoraUIBaseViews/AgoraUIBaseViews.podspec'
  pod 'AgoraExtApp', :path => '../AgoraExtApp/AgoraExtApp.podspec'
  pod 'AgoraWidget', :path => '../AgoraWidget/AgoraWidget.podspec'
  pod 'AgoraEduContext', :path => '../AgoraEduContext/AgoraEduContext.podspec'

  # Pods for AgoraEduContext
  post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
             config.build_settings['ENABLE_BITCODE'] = 'YES'
         end
     end
  end
  
end
