# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'EduSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AgoraLog', :path => '../AgoraLog/AgoraLog.podspec'
  pod 'AgoraReport', :path => '../AgoraReport/AgoraReport.podspec'
  pod "YYModel", "1.0.4"
  pod "AgoraRtm_iOS", "1.4.1"
  pod "AFNetworking", "4.0.1"
  pod "AgoraRtcEngine_Special_iOS", "2.9.107.136"

  post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
             config.build_settings['ENABLE_BITCODE'] = 'YES'
         end
     end
  end
end
