# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

def libVersion
  # third libs
  pod 'Protobuf', '3.17.0'
  pod "CocoaLumberjack", '3.6.1'
  pod 'AliyunOSSiOS',  '2.10.8'
  pod 'Armin',  '1.0.9'
  pod 'Alamofire', '4.7.3'
  pod 'SSZipArchive', '2.4.2'
  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry', '1.1.0'
  pod 'SDWebImage', '5.12.0'
  pod 'WHToast', '0.0.7'
  pod 'FLAnimatedImage', '1.0.16'

  # agora libs
  pod 'AgoraRtm_iOS', '1.4.8'
  pod 'Whiteboard', '2.16.2'
  pod 'AgoraRtcEngine_iOS', '3.4.6'
  pod 'HyphenateChat', '3.8.6'
end

def preRtc
  pod 'AgoraEduCore/PreRtc', :path => '../../../cloudclass-ios/AgoraEduCore_Local.podspec'
  pod 'AgoraRte/PreRtc', :path => '../../../common-scene-sdk/iOS/AgoraRte.podspec'
  pod "AgoraRtcEngine_iOS", "3.4.6"
end

def reRtc
  pod 'AgoraEduCore/ReRtc', :path => '../../../cloudclass-ios/AgoraEduCore_Local.podspec'
  pod 'AgoraRte/ReRtc', :path => '../../../common-scene-sdk/iOS/AgoraRte.podspec'
  pod 'AgoraRtcKit', :path => '../../../common-scene-sdk/iOS/ReRtc/AgoraRtcKit_Binary.podspec'  
end

def openSourceLibs
  # open source libs
  pod 'AgoraEduContext', :path => '../AgoraEduContext/AgoraEduContext_Local.podspec' 
  pod 'AgoraEduUI', :path => '../AgoraEduUI/AgoraEduUI_Local.podspec'
end

def widgetsExtApps
  pod 'AgoraWidgets', :path => '../../../open-apaas-extapp-ios/AgoraWidgets/AgoraWidgets_Local.podspec'
  pod 'AgoraExtApps', :path => '../../../open-apaas-extapp-ios/AgoraExtApps/AgoraExtApps_Local.podspec'
end

def sourcePod
  # close source libs
  pod 'AgoraReport', :path => '../../../apaas-common-libs-ios/SDKs/AgoraReport/AgoraReport.podspec'
  pod 'AgoraRx', :path => '../../../apaas-common-libs-ios/SDKs/AgoraRx/AgoraRx.podspec'
	
  # common libs
  pod 'AgoraWidget', :path => '../../../apaas-common-libs-ios/SDKs/AgoraWidget/AgoraWidget_Local.podspec'
  pod 'AgoraExtApp', :path => '../../../apaas-common-libs-ios/SDKs/AgoraExtApp/AgoraExtApp_Local.podspec'
  pod 'AgoraUIBaseViews', :path => '../../../apaas-common-libs-ios/SDKs/AgoraUIBaseViews/AgoraUIBaseViews_Local.podspec'  

  # rtc
  preRtc
end

def binaryPod
  pod 'AgoraEduCore'

  # common libs
  pod 'AgoraUIBaseViews'
  pod 'AgoraWidget'
  pod 'AgoraExtApp'
end

target 'AgoraClassroomSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  libVersion
  
  openSourceLibs
  widgetsExtApps

  sourcePod
  #binaryPod
  
  post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
             config.build_settings['ENABLE_BITCODE'] = 'YES'
             config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
         end
     end
  end
end
