# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

def libVersion
  # third libs
  pod 'Protobuf', '3.17.0'
  pod "CocoaLumberjack", '3.6.1'
  pod 'AliyunOSSiOS',  '2.10.8'
  pod 'Armin',  '1.1.0'
  pod 'SSZipArchive', '2.4.2'
  pod 'SwifterSwift', '5.2.0'
  pod 'Masonry', '1.1.0'
  pod 'SDWebImage', '5.12.0'
  pod 'WHToast', '0.0.7'
  pod 'FLAnimatedImage', '1.0.16'

  # agora libs
  pod 'AgoraRtm_iOS', '1.4.8'
  pod 'AgoraMediaPlayer_iOS', '1.3.0'
  pod 'AgoraRtcEngine_iOS', '3.5.2'
  pod 'Whiteboard', '2.16.24'
  pod 'Agora_Chat_iOS', '1.0.6.1'
end

def preRtc
  pod 'AgoraEduCore/PreRtc', :path => '../../../cloudclass-ios/AgoraEduCore_Local.podspec'
  pod 'AgoraRte/PreRtc', :path => '../../../common-scene-sdk/iOS/AgoraRte.podspec'
  pod "AgoraRtcEngine_iOS", "3.5.2"
end

def reRtc
  pod 'AgoraEduCore/ReRtc', :path => '../../../cloudclass-ios/AgoraEduCore_Local.podspec'
  pod 'AgoraRte/ReRtc', :path => '../../../common-scene-sdk/iOS/AgoraRte.podspec'
  pod 'AgoraRtcKit', :path => '../../../common-scene-sdk/iOS/ReRtc/AgoraRtcKit_Binary.podspec'  
end

def openSourceLibs
  # open source libs
  pod 'AgoraEduContext', :path => '../../AgoraEduContext.podspec' 
  pod 'AgoraEduUI', :path => '../../AgoraEduUI.podspec'
end

def widgets
  pod 'AgoraWidgets', :path => '../../../open-apaas-extapp-ios/AgoraWidgets.podspec'
end

def sourcePod
  # close source libs
  pod 'AgoraReport', :path => '../../../apaas-common-libs-ios/SDKs/AgoraReport/AgoraReport.podspec'
  pod 'AgoraRx', :path => '../../../apaas-common-libs-ios/SDKs/AgoraRx/AgoraRx.podspec'
	
  # common libs
  pod 'AgoraWidget', :path => '../../../apaas-common-libs-ios/SDKs/AgoraWidget/AgoraWidget_Local.podspec'
  pod 'AgoraUIBaseViews', :path => '../../../apaas-common-libs-ios/SDKs/AgoraUIBaseViews/AgoraUIBaseViews_Local.podspec'  

  # rtc
  preRtc
end

def binaryPod
  pod 'AgoraEduCore'

  # common libs
  pod 'AgoraUIBaseViews'
  pod 'AgoraWidget'
end

target 'AgoraClassroomSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  libVersion
  
  openSourceLibs
  widgets

  sourcePod
  #binaryPod
end
