# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

def libVersion
  pod 'Protobuf', '3.17.0'
  pod "AFNetworking", "4.0.1"
  pod "CocoaLumberjack", "3.6.1"
  pod "AliyunOSSiOS", "2.10.8"
  pod "Armin", "1.0.8"
  pod "Alamofire", "4.7.3"
  pod "SSZipArchive", "2.4.2"

  pod "Whiteboard", "2.15.1"
  pod "AgoraRtm_iOS", "1.4.8"

  pod "SwifterSwift", "5.2.0" 
  pod "Masonry"
end

def preRtc
  pod 'AgoraEduCore/PreRtc', :path => '../../../cloudclass-ios/SDKs/AgoraEduCoreFull.podspec'

  #pod 'AgoraEduCorePuppet/PreRtc', :path => '../../../cloudclass-ios/SDKs/AgoraEduCorePuppet/AgoraEduCorePuppet_Local.podspec'
  #pod 'AgoraEduCore/PreRtc', :path => '../../../cloudclass-ios/SDKs/AgoraEduCore/AgoraEduCore_Local.podspec'
  pod 'AgoraRte/PreRtc', :path => '../../../common-scene-sdk/iOS/AgoraRte.podspec'
  pod "AgoraRtcEngine_iOS", "3.4.6"
end

def reRtc
  pod 'AgoraEduCorePuppet/ReRtc', :path => '../../../cloudclass-ios/SDKs/AgoraEduCorePuppet/AgoraEduCorePuppet_Local.podspec'
  pod 'AgoraEduCore/ReRtc', :path => '../../../cloudclass-ios/SDKs/AgoraEduCore/AgoraEduCore_Local.podspec'
  pod 'AgoraRte/ReRtc', :path => '../../../common-scene-sdk/iOS/AgoraRte.podspec'
  pod 'AgoraRtcKit', :path => '../../../common-scene-sdk/iOS/ReRtc/AgoraRtcKit_Binary.podspec'  
end

def openSourceLibs
  # open source libs
  pod 'AgoraEduContext', :path => '../AgoraEduContext/AgoraEduContext.podspec' 
  pod 'AgoraEduUI', :path => '../AgoraEduUI/AgoraEduUI.podspec'
  pod 'AgoraUIEduBaseViews', :path => '../Modules/AgoraUIEduBaseViews/AgoraUIEduBaseViews_Local.podspec'
end

def widgets
  pod 'AgoraWidgets', :path => '../../Widgets/AgoraWidgets/AgoraWidgets.podspec'
  pod 'ChatWidget', :path => '../../Widgets/ChatWidget/ChatWidget.podspec'
end

def sourcePod
  # close source libs
  pod 'AgoraWhiteBoard', :path => '../../../cloudclass-ios/SDKs/Modules/AgoraWhiteBoard/AgoraWhiteBoard.podspec'
  #pod 'AgoraReport', :path => '../../../cloudclass-ios/SDKs/Modules/AgoraReport/AgoraReport.podspec'
  #pod 'AgoraRx', :path => '../../../cloudclass-ios/SDKs/Modules/AgoraRx/AgoraRx.podspec'
	
  # common libs
  pod 'AgoraWidget', :path => '../../../apaas-common-libs-ios/SDKs/AgoraWidget/AgoraWidget_Local.podspec'
  pod 'AgoraExtApp', :path => '../../../apaas-common-libs-ios/SDKs/AgoraExtApp/AgoraExtApp_Local.podspec'
  pod 'AgoraUIBaseViews', :path => '../../../apaas-common-libs-ios/SDKs/AgoraUIBaseViews/AgoraUIBaseViews_Local.podspec'  

  # rtc
  preRtc
end

def binaryPod
  pod 'AgoraEduCore'

  # common libs
  pod 'AgoraUIBaseViews'
  pod 'AgoraWidget'
  pod 'AgoraExtApp'
end

target 'AgoraClassroomSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  libVersion
  
  openSourceLibs
  widgets	

  sourcePod
  #binaryPod
  
  post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
             config.build_settings['ENABLE_BITCODE'] = 'YES'
             config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
         end
     end
  end
end
